package model.services;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 29 10:51:50 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for XxOmFinanceTVO1.
     * @return XxOmFinanceTVO1
     */
    public ViewObjectImpl getXxOmFinanceTVO1() {
        return (ViewObjectImpl) findViewObject("XxOmFinanceTVO1");
    }

    /**
     * Container's getter for choicelistlov1.
     * @return choicelistlov1
     */
    public ViewObjectImpl getchoicelistlov1() {
        return (ViewObjectImpl) findViewObject("choicelistlov1");
    }

    /**
     * Container's getter for ranze1.
     * @return ranze1
     */
    public ViewObjectImpl getranze1() {
        return (ViewObjectImpl) findViewObject("ranze1");
    }
}

